require: rubocop-rails

AllCops:
  Exclude:
    # App files
    - "app/channels/application_cable/**/*"
    - "app/graphql/kiln_backend_schema.rb"
    - "app/jobs/application_job.rb"
    - "app/mailers/application_mailer.rb"
    - "app/models/application_record.rb"
    - "bin/**/*"
    - "config.ru"
    - "config/**/*"
    - "db/**/*"
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    # Added files to review
    - "app/controllers/graphql_controller.rb"
    - "app/graphql/types/base_*"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
