name: RSpec Tests

on:
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: kiln_backend_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-intervale 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Database Migrations
        run: bundle exec rails db:migrate RAILS_ENV=test

      - name: "Run RSpec Tests"
        run: bundle exec rspec
